# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WtCli < Formula
  desc "Ergonomic git worktrees: create, list, switch, rename, remove"
  homepage "https://github.com/didley/wt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/didley/wt/releases/download/v0.1.0/wt_0.1.0_darwin_amd64.tar.gz"
      sha256 "1127d454adbfac1c8932cb961f5556de00e8bac81fd9c9be1f2d77bce677fed7"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/didley/wt/releases/download/v0.1.0/wt_0.1.0_darwin_arm64.tar.gz"
      sha256 "6185f4f5613440e49d62f9229562e998e392f150501aac0aab7ef261117bf79b"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.1.0/wt_0.1.0_linux_amd64.tar.gz"
      sha256 "ddae0d2e819c698cae346dedb41d8dd7e0af9f46dc5d1d013acfb9ad357a4501"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.1.0/wt_0.1.0_linux_arm64.tar.gz"
      sha256 "dcaf7bd6c0ae3823b99021e81294655f351646ee0e32fffaa4b6eaca086f1296"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
