# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WtCli < Formula
  desc "Ergonomic git worktrees: create, list, switch, rename, remove"
  homepage "https://github.com/didley/wt"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/didley/wt/releases/download/v0.3.3/wt_0.3.3_darwin_amd64.tar.gz"
      sha256 "04f12476d9f005127f3bbf431a638b86f50a21c2a285a974e075db573f370727"

      define_method(:install) do
        bin.install "wt"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/didley/wt/releases/download/v0.3.3/wt_0.3.3_darwin_arm64.tar.gz"
      sha256 "834f4b2e9765a24a82379fdd64d0472c93a73782ae02bcd886d892d7ec91aaec"

      define_method(:install) do
        bin.install "wt"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.3.3/wt_0.3.3_linux_amd64.tar.gz"
      sha256 "0c02f85bad27cc0cb35ed98e4a91b5c7417b2c808a66aefe65e79e4316eb3ee5"
      define_method(:install) do
        bin.install "wt"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.3.3/wt_0.3.3_linux_arm64.tar.gz"
      sha256 "5206d184ad1cbb5713999af4fc893e2b67337566a63b66936f799114d5a55134"
      define_method(:install) do
        bin.install "wt"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
