# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WtCli < Formula
  desc "Ergonomic git worktrees: create, list, switch, rename, remove"
  homepage "https://github.com/didley/wt"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/didley/wt/releases/download/v0.2.6/wt_0.2.6_darwin_amd64.tar.gz"
      sha256 "c4344f766795793b00df4f81e502b4bdc39f1fa3f27eb8125343bcd9ce08d8f0"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/didley/wt/releases/download/v0.2.6/wt_0.2.6_darwin_arm64.tar.gz"
      sha256 "457491981187b4a2a3a3d3057e7d3e577c19bae2d9f3ca605c004f3e5eacdbb2"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.2.6/wt_0.2.6_linux_amd64.tar.gz"
      sha256 "3cce8a6387b1652c3a9b3f7e4dc952df8128f26c088065846a89a077b045e497"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.2.6/wt_0.2.6_linux_arm64.tar.gz"
      sha256 "9afae7d1f4b937974986385e9bd1064af5b303de758ea63e086a0901f5cbe4eb"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
