# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WtCli < Formula
  desc "Ergonomic git worktrees: create, list, switch, rename, remove"
  homepage "https://github.com/didley/wt"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/didley/wt/releases/download/v0.3.1/wt_0.3.1_darwin_amd64.tar.gz"
      sha256 "2ab9aa2eb4e270f19b31b216cab5735f638a7f6492145c3ed5d77e5848712964"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/didley/wt/releases/download/v0.3.1/wt_0.3.1_darwin_arm64.tar.gz"
      sha256 "ceee37eacb098ab351de3f38d4ba5235e2bd227e8e617f7820485c464573cdf7"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.3.1/wt_0.3.1_linux_amd64.tar.gz"
      sha256 "b49d2456093a0a40c8bd8453a0a31dc7a7fb39d44e1129fe2a4942410abef326"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/didley/wt/releases/download/v0.3.1/wt_0.3.1_linux_arm64.tar.gz"
      sha256 "caa64a7d41534ee551110c7dea46d72b0e71ab33b5c6aa6c7eacadc78d828b44"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
